import type { NextPage } from "next";
import Head from "next/head";
import KakaoLogin from "@components/KaKaoLogin";
import Modal from "@components/base/Modal";

const Login: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <KakaoLogin
      token={process.env.NEXT_PUBLIC_KAKAO_LOGIN_KEY as string}
      onSuccess={(result) => {
        alert(`로그인에 성공하셨습니다. ${JSON.stringify(result)}`);
        console.log(result);
      }}
      onFail={(result) => {
        alert(`로그인에 실패하셨습니다. ${JSON.stringify(result)}`);
        console.log(result);
      }}
      onLogout={() => {
        alert(`로그아웃 하셨습니다.`);
      }}
    />
  </div>
);

export default Login;
