// MDN | Key Values 문서를 참조
// https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

// freeCodeCamp | JavaScript Keycode List 문서를 참조
// https://www.freecodecamp.org/news/javascript-keycode-list-keypress-event-key-codes/

export type EventKeyValue =
  // Open Type for any key needed
  | string

  // Alphabet keys
  | 'a'
  | 'b'
  | 'c'
  | 'd'
  | 'e'
  | 'f'
  | 'g'
  | 'h'
  | 'i'
  | 'j'
  | 'k'
  | 'l'
  | 'm'
  | 'n'
  | 'o'
  | 'p'
  | 'q'
  | 'r'
  | 's'
  | 't'
  | 'u'
  | 'v'
  | 'w'
  | 'x'
  | 'y'
  | 'z'

  // Special Characters
  | ';'
  | '='
  | ','
  | '-'
  | '.'
  | '/'
  | '`'
  | '['
  | '\\'
  | ']'
  | "'"

  // Browser control keys
  | 'BrowserBack'
  | 'BrowserFavorites'
  | 'BrowserForward'
  | 'BrowserHome'
  | 'BrowserRefresh'
  | 'BrowserSearch'
  | 'BrowserStop'

  // Numeric keypad keys
  | 'Decimal'
  | 'Key11'
  | 'Key12'
  | 'Multiply'
  | 'Add'
  | 'Clear'
  | 'Divide'
  | 'Subtract'
  | 'Separator'
  | '*'
  | '+'
  | '-'
  | '.'
  | '/'
  | '0'
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'

  // Special values
  | 'Unidentified'

  // Modifier keys
  | 'Alt'
  | 'AltGraph'
  | 'CapsLock'
  | 'Control'
  | 'Fn'
  | 'FnLock'
  | 'Hyper'
  | 'Meta'
  | 'NumLock'
  | 'ScrollLock'
  | 'Shift'
  | 'Super'
  | 'Symbol'
  | 'SymbolLock'

  // Whitespace keys
  | 'Enter'
  | 'Tab'
  | ' ' // The space key, Space Bar

  // Navigation keys
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'ArrowUp'
  | 'End'
  | 'Home'
  | 'PageDown'
  | 'PageUp'

  // Editing keys
  | 'Backspace'
  | 'Clear'
  | 'Copy'
  | 'CrSel'
  | 'Cut'
  | 'Delete'
  | 'EraseEof'
  | 'ExSel'
  | 'Insert'
  | 'Paste'
  | 'Redo'
  | 'Undo'

  // UI keys
  | 'Accept'
  | 'Again'
  | 'Attn'
  | 'Cancel'
  | 'ContextMenu'
  | 'Escape'
  | 'Execute'
  | 'Find'
  | 'Finish'
  | 'Help'
  | 'Pause'
  | 'Play'
  | 'Props'
  | 'Select'
  | 'ZoomIn'
  | 'ZoomOut'

  // Device keys
  | 'BrightnessDown'
  | 'BrightnessUp'
  | 'Eject'
  | 'LogOff'
  | 'Power'
  | 'PowerOff'
  | 'PrintScreen'
  | 'Hibernate'
  | 'Standby'
  | 'WakeUp'

  // IME and composition keys
  | 'AllCandidates'
  | 'Alphanumeric'
  | 'CodeInput'
  | 'Compose'
  | 'Convert'
  | 'Dead'
  | 'FinalMode'
  | 'GroupFirst'
  | 'GroupLast'
  | 'GroupNext'
  | 'GroupPrevious'
  | 'ModeChange'
  | 'NextCandidate'
  | 'NonConvert'
  | 'PreviousCandidate'
  | 'Process'
  | 'SingleCandidate'

  // Korean keyboards only
  | 'HangulMode'
  | 'HanjaMode'
  | 'JunjaMode'

  // Japanese keyboards only
  | 'Eisu'
  | 'Hankaku'
  | 'Hiragana'
  | 'HiraganaKatakana'
  | 'KanaMode'
  | 'KanjiMode'
  | 'Katakana'
  | 'Romaji'
  | 'Zenkaku'
  | 'ZenkakuHanaku'

  // TODO: Skipped Dead keycodes for Linux

  // Function keys
  | 'F1'
  | 'F2'
  | 'F3'
  | 'F4'
  | 'F5'
  | 'F6'
  | 'F7'
  | 'F8'
  | 'F9'
  | 'F10'
  | 'F11'
  | 'F12'
  | 'F13'
  | 'F14'
  | 'F15'
  | 'F16'
  | 'F17'
  | 'F18'
  | 'F19'
  | 'Soft1'
  | 'Soft2'
  | 'Soft3'
  | 'Soft4'

  // Phone keys
  | 'AppSwitch'
  | 'Call'
  | 'Camera'
  | 'CameraFocus'
  | 'EndCall'
  | 'GoBack'
  | 'GoHome'
  | 'HeadsetHook'
  | 'LastNumberRedial'
  | 'Notification'
  | 'MannerMode'
  | 'VoiceDial'

  // Multimedia keys
  | 'ChannelDown'
  | 'ChannelUp'
  | 'MediaFastForward'
  | 'MediaPause'
  | 'MediaPlay'
  | 'MediaPlayPause'
  | 'MediaRecord'
  | 'MediaRewind'
  | 'MediaStop'
  | 'MediaTrackNext'
  | 'MediaTrackPrevious'

  // Audio control keys
  | 'AudioBalanceLeft'
  | 'AudioBalanceRight'
  | 'AudioBassDown'
  | 'AudioBassBoostDown'
  | 'AudioBassBoostToggle'
  | 'AudioBassBoostUp'
  | 'AudioBassUp'
  | 'AudioFaderFront'
  | 'AudioFaderRear'
  | 'AudioSurroundModeNext'
  | 'AudioTrebleDown'
  | 'AudioTrebleUp'
  | 'AudioVolumeDown'
  | 'AudioVolumeMute'
  | 'AudioVolumeUp'
  | 'MicrophoneToggle'
  | 'MicrophoneVolumeDown'
  | 'MicrophoneVolumeMute'
  | 'MicrophoneVolumeUp'

  // TV control keys
  | 'TV'
  | 'TV3DMode'
  | 'TVAntennaCable'
  | 'TVAudioDescription'
  | 'TVAudioDescriptionMixDown'
  | 'TVAudioDescriptionMixUp'
  | 'TVContentsMenu'
  | 'TVDataService'
  | 'TVInput'
  | 'TVInputComponent1'
  | 'TVInputComponent2'
  | 'TVInputComposite1'
  | 'TVInputComposite2'
  | 'TVInputHDMI1'
  | 'TVInputHDMI2'
  | 'TVInputHDMI3'
  | 'TVInputHDMI4'
  | 'TVInputVGA1'
  | 'TVMediaContext'
  | 'TVNetwork'
  | 'TVNumberEntry'
  | 'TVPower'
  | 'TVRadioService'
  | 'TVSatellite'
  | 'TVSatelliteBS'
  | 'TVSatelliteCS'
  | 'TVSatelliteToggle'
  | 'TVTerrestrialAnalog'
  | 'TVTerrestrialDigital'
  | 'TVTimer'

  // Media controller keys
  | 'AVRInput'
  | 'AVRPower'
  | 'ColorF0Red'
  | 'ColorF1Green'
  | 'ColorF2Yellow'
  | 'ColorF3Blue'
  | 'ColorF4Grey'
  | 'ColorF5Brown'
  | 'ClosedCaptionToggle'
  | 'Dimmer'
  | 'DisplaySwap'
  | 'DVR'
  | 'Exit'
  | 'FavoriteClear0'
  | 'FavoriteClear1'
  | 'FavoriteClear2'
  | 'FavoriteClear3'
  | 'FavoriteRecall0'
  | 'FavoriteRecall1'
  | 'FavoriteRecall2'
  | 'FavoriteRecall3'
  | 'FavoriteStore0'
  | 'FavoriteStore1'
  | 'FavoriteStore2'
  | 'FavoriteStore3'
  | 'Guide'
  | 'GuideNextDay'
  | 'GuidePreviousDay'
  | 'Info'
  | 'InstantReplay'
  | 'Link'
  | 'ListProgram'
  | 'LiveContent'
  | 'Lock'
  | 'MediaApps'
  | 'MediaAudioTrack'
  | 'MediaLast'
  | 'MediaSkipBackward'
  | 'MediaSkipForward'
  | 'MediaStepBackward'
  | 'MediaStepForward'
  | 'MediaTopMenu'
  | 'NavigateIn'
  | 'NavigateNext'
  | 'NavigateOut'
  | 'NavigatePrevious'
  | 'NextFavoriteChannel'
  | 'NextUserProfile'
  | 'OnDemand'
  | 'Pairing'
  | 'PinPDown'
  | 'PinPMove'
  | 'PinPToggle'
  | 'PinPUp'
  | 'PlaySpeedDown'
  | 'PlaySpeedReset'
  | 'PlaySpeedUp'
  | 'RandomToggle'
  | 'RcLowBattery'
  | 'RecordSpeedNext'
  | 'RfBypass'
  | 'ScanChannelsToggle'
  | 'ScreenModeNext'
  | 'Settings'
  | 'SplitScreenToggle'
  | 'STBInput'
  | 'STBPower'
  | 'Subtitle'
  | 'Teletext'
  | 'VideoModeNext'
  | 'Wink'
  | 'ZoomToggle'

  // Speech recognition keys
  | 'SpeechCorrectionList'
  | 'SpeechInputToggle'

  // Document keys
  | 'Close'
  | 'New'
  | 'Open'
  | 'Print'
  | 'Save'
  | 'SpellCheck'
  | 'MailForward'
  | 'MailReply'
  | 'MailSend'

  // Application selector keys
  | 'LaunchCalculator'
  | 'LaunchCalendar'
  | 'LaunchContacts'
  | 'LaunchMail'
  | 'LaunchMediaPlayer'
  | 'LaunchMusicPlayer'
  | 'LaunchMyComputer'
  | 'LaunchPhone'
  | 'LaunchScreenSaver'
  | 'LaunchSpreadsheet'
  | 'LaunchWebBrowser'
  | 'LaunchWebCam'
  | 'LaunchWordProcessor'
  | 'LaunchApplication1'
  | 'LaunchApplication2'
  | 'LaunchApplication3'
  | 'LaunchApplication4'
  | 'LaunchApplication5'
  | 'LaunchApplication6'
  | 'LaunchApplication7'
  | 'LaunchApplication8'
  | 'LaunchApplication9'
  | 'LaunchApplication10'
  | 'LaunchApplication11'
  | 'LaunchApplication12'
  | 'LaunchApplication13'
  | 'LaunchApplication14'
  | 'LaunchApplication15'
  | 'LaunchApplication16'
