export const authTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER",
  LOADING_ON: "LOADING_ON",
  LOADING_OFF: "LOADING_OFF",
  GET_MY_FAVORITES: "SET_MY_FAVORITES",
  CREATE_FAVORITE: "CREATE_FAVORITE",
  DELETE_FAVORITE: "DELETE_FAVORITE",
  PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
  SET_MY_RESERVATIONS: "SET_MY_RESERVATIONS",
} as const;

export type ActionType = typeof authTypes;
export type ActionTypeUnion = ActionType[keyof ActionType];
